# Generated by Django 2.2.4 on 2019-08-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('rne', models.CharField(max_length=255, verbose_name='Rne')),
                ('pais_de_origem', models.CharField(max_length=255, verbose_name='País de Origem')),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=255, verbose_name='Gênero')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=10, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('apresentacao', models.TextField(blank=True, null=True)),
                ('area', models.CharField(choices=[('Comunicação', 'Comunicação'), ('Saúde', 'Saúde'), ('Tecnologia', 'Tecnologia'), ('Financeiro', 'Financeiro'), ('Administração', 'Administração'), ('RH', 'RH'), ('Jurídica', 'Jurídica'), ('Outro', 'Outro')], max_length=255, verbose_name='Áreas')),
                ('area_outros', models.CharField(blank=True, max_length=22, null=True, verbose_name='Caso outra, qual?')),
                ('data_de_criacao', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('data_de_criacao', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
