# Generated by Django 2.2.4 on 2019-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190808_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='escolaridade',
            field=models.CharField(choices=[('EFI', 'Ensino Fundamental Incompleto'), ('EFC', 'Ensino Fundamental Cursando'), ('EFCO', 'Ensino Fundamental Completo'), ('EMI', 'Ensino Médio Incompleto'), ('EMC', 'Ensino Médio Cursando'), ('EMCO', 'Ensino Médio Completo'), ('ESI', 'Ensino Superior Incompleto'), ('ESC', 'Ensino Superior Cursando'), ('ESCO', 'Ensino Superior Completo'), ('P', 'Pós Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='SOME STRING', max_length=255, verbose_name='Escolaridade'),
        ),
    ]
