# Generated by Django 2.2.4 on 2019-08-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190818_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.CharField(max_length=11, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(max_length=10, null=True, verbose_name='Telefone'),
        ),
    ]
