# Generated by Django 2.2.4 on 2019-08-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190819_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='formacao',
            field=models.TextField(blank=True, null=True, verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='idioma',
            field=models.TextField(blank=True, null=True, verbose_name='Idioma'),
        ),
    ]
