# Generated by Django 2.2.4 on 2019-08-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190819_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=None, to='website.Candidato'),
        ),
    ]
