# Generated by Django 2.2.4 on 2019-08-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190819_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='apresentacao',
            field=models.TextField(blank=True, null=True, verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=None, to='website.Candidato', verbose_name='Candidato'),
        ),
    ]
