# Generated by Django 2.2.3 on 2019-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190819_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
