# Generated by Django 2.2.4 on 2019-08-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_curriculo_ativo'),
        ('website', '0013_auto_20190819_1537'),
    ]

    operations = [
    ]
